"""baseline

Revision ID: ed002c071d3e
Revises: 
Create Date: 2025-08-30 00:54:34.256003

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed002c071d3e'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_constraint(op.f('stocks_symbol_key'), 'stocks', type_='unique')
    op.create_index(op.f('ix_stocks_symbol'), 'stocks', ['symbol'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stocks_symbol'), table_name='stocks')
    op.create_unique_constraint(op.f('stocks_symbol_key'), 'stocks', ['symbol'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    # ### end Alembic commands ###
