version: '3.9'
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: flowsnipr
      POSTGRES_PASSWORD: flowsnipr
      POSTGRES_DB: flowsnipr
    ports:
      - "5432:5432"
    volumes:
      - dbdata:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"
volumes:
  dbdata:
